# Generated by Django 4.1.1 on 2022-10-02 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='motDepass',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.MinLengthValidator(8, message='Veuillez taper un mot de passe à 8 caractère min')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel',
            name='role',
            field=models.CharField(choices=[('Administrateur', 'Administrateur')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
