# Generated by Django 4.1.1 on 2022-10-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcApp', '0003_reservation_ressource_reservant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date_joined',
            new_name='date_de_reservation',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='objet_reser',
            new_name='motif_de_reservation',
        ),
    ]
