# Generated by Django 4.1.1 on 2022-10-03 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srcApp', '0002_personnel_motdepass_personnel_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('objet_reser', models.CharField(max_length=255)),
                ('reservateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcApp.personnel')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcApp.ressource')),
            ],
        ),
        migrations.AddField(
            model_name='ressource',
            name='reservant',
            field=models.ManyToManyField(through='srcApp.Reservation', to='srcApp.personnel'),
        ),
    ]
