# Generated by Django 4.1.1 on 2022-10-06 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srcApp', '0004_rename_date_joined_reservation_date_de_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='motDepass',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='username',
        ),
        migrations.AddField(
            model_name='personnel',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
