# Generated by Django 4.1.1 on 2022-10-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcApp', '0005_remove_personnel_motdepass_remove_personnel_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='typeRess',
            field=models.CharField(choices=[('Matériel', 'Matériel')], max_length=20),
        ),
    ]
