# Generated by Django 4.1.1 on 2022-10-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcApp', '0008_alter_ressource_typeress'),
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeRess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeType', models.CharField(max_length=4)),
                ('ress', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='reservant',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='typeRess',
        ),
    ]
