# Generated by Django 4.1.1 on 2022-10-09 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srcApp', '0009_role_typeress_remove_ressource_reservant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='typeRess',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srcApp.typeress'),
        ),
    ]
