# Generated by Django 4.1.1 on 2022-10-09 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcApp', '0011_alter_personnel_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='account',
            new_name='compte',
        ),
    ]
